server:
  port: 8080

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    check-template-location: true
    charset: UTF-8
    enabled: true
    suffix: .html

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jason
    url:  jdbc:mysql://localhost:3306/springboot-all-configs?useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      springframework:
        web: debug


cn:
  jsbintask:
    name: jason
    age: 22
